---
galaxy_info:
  author: roquie
  description: Install Kontena Master on server.
  license: MIT
  min_ansible_version: 2.2
  platforms:
    - name: Ubuntu
      versions:
        - xenial
  galaxy_tags:
    - kontena
    - docker

dependencies: []
