---

# Ansible
ansible_python_interpreter: "/usr/bin/python3"
ansible_ssh_port: 22
ansible_ssh_user: "vagrant"
ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"

# Locales
locales_present:
  - en_US.UTF-8

locales_default:
  lang: en_US.UTF-8

# Docker
docker_package: "docker-ce=17.03*" # if kontena has >=1.4.version, you can use latest version of docker.

